# Generated by Django 6.0.3 on 2026-03-12 12:00

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(validators=[notes.models.validate_min_length])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
